### ISSUE TITLE
Duplicate invitations !

### ISSUE THREAD

**Issue by abada** [junaidnasir/larainvite#1]
I think invitation must be unique per email !

**Comment by junaidnasir** [comment]
that was a design call, e.g if you offer reward system and two users want to invite same person. or did you mean to avoid multiple invitations to same id by same person ?

**Comment by abada** [comment]
The main purpose is when use `$user->invitations()->count();` return also duplicate (invitations) emails , and i think this is not logic .

Thank you for agreat library 👍

**Comment by junaidnasir** [comment]
yeah you are right, will add uniqueness settings in next release. 
meanwhile you can use something like this 
`$user->invitations()->distinct('email')->count('email')` 
also you can use all the Laravel functions like `$user->invitations()->where('status','!=',' expired')->count()`

**Comment by abada** [comment]
Thank you 👍
