### ISSUE TITLE
Can be configure name of attribute insead of user_id

### ISSUE THREAD

**Issue by mknparreira** [junaidnasir/larainvite#12]
First of all, it's a great library. 

I would like to propose a way to change the name of the attribute **user_id** into **user_invitations** table. 

For instance, I've been working with the following settings:  

**Account** 
user_id
company_id

**User**
id
name

**Company**
id
name

In my case, the responsibility for making invitations is Account Model, instead of Auth/User.

Ok,  I 'll save the account_id into user_invitations table as the user_id attribute, but if I could configure the name of the attribute, could be easy to identify the relation. 

You understand that I mean?

**Comment by junaidnasir** [comment]
Hi @mknparreira, Yes that makes sense in the use case. I am busy with other projects at the moment but feel free to open a PR. or maybe I can make some changes next month.
