### ISSUE TITLE
Call to undefined method Illuminate\Events\Dispatcher::fire()

### ISSUE THREAD

**Issue by NikolaIdjos** [junaidnasir/larainvite#16]
Please add new version and change fire to dispach

**Comment by junaidnasir** [comment]
Hi, 
should be fixed in https://github.com/junaidnasir/larainvite/releases/tag/v2.0.0

**Comment by NikolaIdjos** [comment]
Thats ok, but composer latest version is still 0.1.11 with fire method

**Comment by NikolaIdjos** [comment]
???

**Comment by junaidnasir** [comment]
you need to update `composer.json` if you have fixed it to a prior version.

**Comment by NikolaIdjos** [comment]
Its ok now. Thank you
