### ISSUE TITLE
Laravel 6.0 support

### ISSUE THREAD

**Issue by DariusIII** [junaidnasir/larainvite#19]
I , and probably other users too, would like to have Laravel 6.0 supported by this package.

**Comment by junaidnasir** [comment]
Hi @DariusIII, 
I have very little time nowadays to maintain the package but a PR is always welcome

**Comment by DariusIII** [comment]
Hi @junaidnasir ,
I have made a PR which adds Laravel 6.0 support, but it will require major version update as adding DeferrableProvider is not supported in Laravel 5.x.
