### ISSUE TITLE
Can you add phonenumber

### ISSUE THREAD

**Issue by marijang** [junaidnasir/larainvite#2]
Hey this is great package. I need user phone number because i m building social app. Can u add this functionality?

Thanks:D

**Comment by marijang** [comment]
My scenario is next
1. User A have my (mobile) app and he wants to invite by phone number his friend. 
2. User A selects friend or friends from contacts (phone)
3. I create text message for user A which he is sending (sms message) to the phone numbers
4. In text message is invite code (same for all users) but before in my laravel i need to create universal invite with all phone numbers so i can later connect automaticly that users in the app.

**Comment by junaidnasir** [comment]
I am planning to change `email` to `key` so that you can store any type of data, but this would also require validation methods and custom validator handler. will try to release it in next version but may take some time as i am swamped right now.

**Comment by marijang** [comment]
I think you don't need for first version validate phone. Ok for email but for phone it is not required.
if you add key and value 

for example 
key      value               user_id
email   m@m.com       1 
phone 555-555-555    1

I think it is enough
