### ISSUE TITLE
Maintainer proposal

### ISSUE THREAD

**Issue by FredericTribu** [junaidnasir/larainvite#34]
Hello,

I have no idea how to contact you directly, so I create this issue because I'm willing to be the new maintainer of this project.

I'm using it and currently working on a fork to meet our needs.

What would be the conditions to be the new maintainer ?

Regards,
Fred

**Comment by junaidnasir** [comment]
Hi Apologies for such a delay, I have added you as a collaborator on the repo.

**Comment by FredericTribu** [comment]
Sorry, I was sick for 10 days and the invitation expired. Can you send it back ?

**Comment by junaidnasir** [comment]
sent @FredericTribu
